name: Continuous integration
on:
  - push
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build 
        run: cargo build --verbose
      - name: Format 
        run: cargo fmt --check --verbose
      - name: Test 
        run: cargo test --verbose
